#!/bin/bash
# This script is used to activate the VMware development environment.

set -ex

vmrun="/Applications/VMware\ Fusion.app/Contents/Public/vmrun"

echo "Activating development environment..."
ssh mac-vm-host "$vmrun revertToSnapshot \$HOME/Virtual\ Machines.localized/macOS\ 10.13\ High\ Sierra.vmwarevm/ PyInstallerDevelopment"
echo "Development snapshot restored. Starting the VMware development environment."
ssh mac-vm-host "$vmrun start \$HOME/Virtual\ Machines.localized/macOS\ 10.13\ High\ Sierra.vmwarevm/"
echo "VMware development environment is now running."
